--- #YAML:1.0
name:                AnyEvent-STOMP
version:             0.5
abstract:            A lightweight event-driven STOMP client
license:             perl
author:              
    - Michael S. Fischer <michael+cpan@dynamine.net>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    AnyEvent:                      5
    common::sense:                 1
    Object::Event:                 1.21
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
